create table if not exists public.secret_messages (
    id bigint generated by default as identity primary key,
    content text not null,
    created_at timestamptz not null default timezone('utc', now())
);

comment on table public.secret_messages is '私密留言板消息表，供 secret_board.html 与私密陪伴 AI 使用。';

create index if not exists secret_messages_created_at_idx
    on public.secret_messages (created_at asc, id asc);

alter table public.secret_messages enable row level security;

revoke all on table public.secret_messages from anon;
revoke all on table public.secret_messages from authenticated;

create table if not exists public.secret_ai_memories (
    scope text primary key,
    memory_summary text not null default '',
    last_message_id bigint not null default 0,
    updated_at timestamptz not null default timezone('utc', now())
);

comment on table public.secret_ai_memories is '私密陪伴 AI 的滚动记忆摘要表，仅服务端可读写。';
comment on column public.secret_ai_memories.scope is '记忆作用域，第一版固定为 secret_board。';
comment on column public.secret_ai_memories.memory_summary is '私密关系与生活语境的滚动摘要。';
comment on column public.secret_ai_memories.last_message_id is '上次已纳入记忆摘要的最大消息 ID。';

alter table public.secret_ai_memories enable row level security;

revoke all on table public.secret_ai_memories from anon;
revoke all on table public.secret_ai_memories from authenticated;

insert into public.secret_ai_memories (scope)
values ('secret_board')
on conflict (scope) do nothing;
